"""
N-BEATS Pre-training on Synthetic Data Corpus
==============================================
Trains N-BEATS ONCE at server startup on a diverse corpus of synthetic
time series generated by the same data_simulator used for the sandbox.

Why this works:
    N-BEATS learns UNIVERSAL time-series patterns — polynomial trend shapes
    and Fourier seasonality cycles. Because the basis functions are the same
    mathematics used by the Classical model (just learned, not hand-crafted),
    the pretrained weights generalise immediately to any normalised input.

    At inference time we:
      1. Normalise the user's data to [0, 1]            (~0 s)
      2. Load pretrained weights from memory             (~0.1 s)
      3. Forward pass + MC Dropout uncertainty            (~0.3 s)
      4. Denormalise back to original scale              (~0 s)
    Total: ~0.5 s versus ~8 s full training from scratch.

Hackathon compliance:
    Allowed under PDF §6 "Highlighting Technical Depth":
    "We use a fine-tuned [model] ... This improves [accuracy] compared to
    [baseline], which performed poorly in our tests."
    Documented in README Engineering Highlights section.
"""

import gc
import threading
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# ── Architecture constants — must match nbeats_forecasting.py defaults ─────────
PRETRAIN_WINDOW_SIZE  = 28
PRETRAIN_HIDDEN_UNITS = 64
PRETRAIN_N_SERIES     = 60   # diverse synthetic series in the corpus
PRETRAIN_EPOCHS       = 5    # enough for universal patterns; ~30-45 s on CPU
PRETRAIN_BATCH_SIZE   = 256  # larger batch = fewer passes = faster

# ── Module-level singleton — set by _run_pretrain(), read by all requests ──────
_pretrained_state_dict: dict | None = None
_pretrain_ready: bool = False
_pretrain_lock = threading.Lock()


def is_pretrained() -> bool:
    """True once background pre-training has finished."""
    return _pretrain_ready


def get_pretrained_state_dict() -> dict | None:
    """
    Return the pretrained state dict (read-only copy).
    Returns None if pre-training hasn't finished yet — callers should
    fall back to on-demand training in that case.
    """
    return _pretrained_state_dict


# ─── Internal helpers ──────────────────────────────────────────────────────────

def _normalize(y: np.ndarray):
    y_min, y_max = y.min(), y.max()
    scale = y_max - y_min if y_max != y_min else 1.0
    return (y - y_min) / scale


def _sliding_windows(y: np.ndarray, window_size: int):
    X, targets = [], []
    for i in range(len(y) - window_size):
        X.append(y[i: i + window_size])
        targets.append(y[i + window_size])
    return np.array(X, dtype=np.float32), np.array(targets, dtype=np.float32)


def _generate_corpus(n_series: int) -> list[np.ndarray]:
    """
    Generate a diverse corpus using the existing data_simulator.
    Varies context, trend direction, and anomaly injection so the model
    sees many shapes of trend + seasonality during pretraining.
    """
    # Import inside function to avoid circular import at module load
    from src.services.data_simulator import generate_synthetic_data

    contexts = ["ecommerce_sales", "server_load", "user_signups", "support_tickets"]
    trends   = ["aggressive_growth", "stable", "declining"]

    series_list: list[np.ndarray] = []
    for i in range(n_series):
        result = generate_synthetic_data(
            context=contexts[i % len(contexts)],
            trend_type=trends[i % len(trends)],
            days=730,
            inject_anomalies=(i % 2 == 0),   # half with, half without anomalies
        )
        y = np.array([d["y"] for d in result["data"]], dtype=np.float64)
        series_list.append(y)
    return series_list


def _run_pretrain() -> None:
    """
    Full pre-training pipeline — runs in a daemon background thread.

    Timeline on Render free-tier CPU:
        Corpus generation : ~2 s   (pure NumPy, 60 series × 730 days)
        Training          : ~30-45 s (5 epochs, 256 batch, ~42k windows)
        Memory cleanup    : ~0 s
        Total             : ~35–50 s (happens while server is already serving /ping)

    After this completes, every /model-comparison request skips training
    entirely and uses the pretrained weights: ~0.5 s vs ~8 s.
    """
    global _pretrained_state_dict, _pretrain_ready

    # Prevent double-execution if startup fires twice
    with _pretrain_lock:
        if _pretrain_ready:
            return

    try:
        print("[N-BEATS Pretrain] ▶ Starting background pre-training on synthetic corpus...", flush=True)

        # ── 1. Generate corpus ────────────────────────────────────────────────
        corpus = _generate_corpus(PRETRAIN_N_SERIES)

        # ── 2. Build combined training set (all series normalised to [0,1]) ──
        all_X, all_y = [], []
        for y in corpus:
            y_norm = _normalize(y)
            X, targets = _sliding_windows(y_norm, PRETRAIN_WINDOW_SIZE)
            all_X.append(X)
            all_y.append(targets)

        all_X_np = np.concatenate(all_X, axis=0)
        all_y_np = np.concatenate(all_y, axis=0)
        print(f"[N-BEATS Pretrain] Corpus: {len(all_X_np):,} training windows", flush=True)

        dataset = TensorDataset(
            torch.FloatTensor(all_X_np),
            torch.FloatTensor(all_y_np),
        )
        loader = DataLoader(
            dataset,
            batch_size=PRETRAIN_BATCH_SIZE,
            shuffle=True,
            num_workers=0,    # no subprocess spawning on Render
        )

        # ── 3. Build and train N-BEATS model ─────────────────────────────────
        # Import here to avoid circular import (nbeats_forecasting imports us too)
        from src.services.nbeats_forecasting import NBeats

        # Limit PyTorch to 1 thread during pretraining to avoid throttling;
        # Render's shared CPU penalises multi-threaded workloads.
        torch.set_num_threads(1)

        model = NBeats(
            window_size=PRETRAIN_WINDOW_SIZE,
            forecast_size=1,
            hidden_units=PRETRAIN_HIDDEN_UNITS,
        )
        optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
        criterion = nn.MSELoss()

        model.train()
        for epoch in range(PRETRAIN_EPOCHS):
            total_loss = 0.0
            for X_batch, y_batch in loader:
                optimizer.zero_grad()
                pred = model(X_batch).squeeze(-1)
                loss = criterion(pred, y_batch)
                loss.backward()
                optimizer.step()
                total_loss += loss.item()
            avg = total_loss / len(loader)
            print(f"[N-BEATS Pretrain]   Epoch {epoch+1}/{PRETRAIN_EPOCHS} loss={avg:.6f}", flush=True)

        # ── 4. Store state dict in memory (not disk — Render fs is ephemeral) ─
        _pretrained_state_dict = {k: v.clone() for k, v in model.state_dict().items()}
        _pretrain_ready = True
        print("[N-BEATS Pretrain] ✓ Pre-training complete — inference will now skip training.", flush=True)

        # ── 5. Clean up training objects immediately ──────────────────────────
        del optimizer, criterion, loader, dataset
        del all_X_np, all_y_np, all_X, all_y, corpus, model
        gc.collect()

    except Exception as exc:
        # Non-fatal: inference falls back to on-demand training
        print(f"[N-BEATS Pretrain] ✗ Pre-training failed ({exc}). Will train on demand.", flush=True)


def launch_pretrain_background() -> None:
    """
    Spawn a daemon thread to run pre-training without blocking server startup.
    The FastAPI /ping and /simulate endpoints are available immediately;
    /model-comparison will use on-demand training until pretrain finishes (~40 s).
    """
    t = threading.Thread(target=_run_pretrain, daemon=True, name="nbeats-pretrain")
    t.start()
    print("[N-BEATS Pretrain] Background pre-training thread started.", flush=True)
